#include <idt/interrupts.h>
#include <goobos/types.h>
#include <vga.h>

const char *exception_vector_strings[EXCEPTION_VECTOR_MAX] = {
    [EXCEPTION_VECTOR_DIVISION_ERROR] = "EXCEPTION_VECTOR_DIVISION_ERROR",
    [EXCEPTION_VECTOR_DEBUG] = "EXCEPTION_VECTOR_DEBUG",
    [EXCEPTION_VECTOR_NON_MASKABLE_INTERRUPT] = "EXCEPTION_VECTOR_NON_MASKABLE_INTERRUPT",
    [EXCEPTION_VECTOR_BREAKPOINT] = "EXCEPTION_VECTOR_BREAKPOINT",
    [EXCEPTION_VECTOR_OVERFLOW] = "EXCEPTION_VECTOR_OVERFLOW",
    [EXCEPTION_VECTOR_BOUND_RANGE_EXCEEDED] = "EXCEPTION_VECTOR_BOUND_RANGE_EXCEEDED",
    [EXCEPTION_VECTOR_INVALID_OPCODE] = "EXCEPTION_VECTOR_INVALID_OPCODE",
    [EXCEPTION_VECTOR_DEVICE_NOT_AVAILABLE] = "EXCEPTION_VECTOR_DEVICE_NOT_AVAILABLE",
    [EXCEPTION_VECTOR_DOUBLE_FAULT] = "EXCEPTION_VECTOR_DOUBLE_FAULT",
    [EXCEPTION_VECTOR_INVALID_TSS] = "EXCEPTION_VECTOR_INVALID_TSS",
    [EXCEPTION_VECTOR_SEGMENT_NOT_PRESENT] = "EXCEPTION_VECTOR_SEGMENT_NOT_PRESENT",
    [EXCEPTION_VECTOR_STACK_SEGMENT_FAULT] = "EXCEPTION_VECTOR_STACK_SEGMENT_FAULT",
    [EXCEPTION_VECTOR_GENERAL_PROTECTION_FAULT] = "EXCEPTION_VECTOR_GENERAL_PROTECTION_FAULT",
    [EXCEPTION_VECTOR_PAGE_FAULT] = "EXCEPTION_VECTOR_PAGE_FAULT",
    [EXCEPTION_VECTOR_X87_FLOATING_POINT_EXCEPTION] = "EXCEPTION_VECTOR_X87_FLOATING_POINT_EXCEPTION",
    [EXCEPTION_VECTOR_ALIGNMENT_CHECK] = "EXCEPTION_VECTOR_ALIGNMENT_CHECK",
    [EXCEPTION_VECTOR_MACHINE_CHECK] = "EXCEPTION_VECTOR_MACHINE_CHECK",
    [EXCEPTION_VECTOR_SIMD_FLOATING_POINT_EXCEPTION] = "EXCEPTION_VECTOR_SIMD_FLOATING_POINT_EXCEPTION",
    [EXCEPTION_VECTOR_VIRTUALIZATION_EXCEPTION] = "EXCEPTION_VECTOR_VIRTUALIZATION_EXCEPTION",
    [EXCEPTION_VECTOR_CONTROL_PROTECTION_EXCEPTION] = "EXCEPTION_VECTOR_CONTROL_PROTECTION_EXCEPTION",
    [EXCEPTION_VECTOR_HYPERVISOR_INJECTION_EXCEPTION] = "EXCEPTION_VECTOR_HYPERVISOR_INJECTION_EXCEPTION",
    [EXCEPTION_VECTOR_VMM_COMMUNICATOR_EXCEPTION] = "EXCEPTION_VECTOR_VMM_COMMUNICATOR_EXCEPTION",
    [EXCEPTION_VECTOR_SECURITY_EXCEPTION] = "EXCEPTION_VECTOR_SECURITY_EXCEPTION",
};

void interrupt_handler(void)
{
    vga_println("INTERRUPT");
}
